---
- name: Deploy Flask Application
  hosts: your_ec2_instance_group
  become: yes
  vars:
    project_path: "{{ lookup('env', 'PROJECT_PATH') | default('/default/path/to/project', true) }}"
    venv_path: "{{ project_path }}/venv"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3 and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Create a virtual environment
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}"

    - name: Install requirements
      pip:
        requirements: "{{ project_path }}/requirements.txt"
        virtualenv: "{{ venv_path }}"

    - name: Install Gunicorn
      pip:
        name: gunicorn
        virtualenv: "{{ venv_path }}"

    - name: Copy Gunicorn systemd service file
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
      notify: restart gunicorn

    - name: Enable and start Gunicorn
      systemd:
        name: gunicorn
        enabled: yes
        state: started

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy Nginx configuration for the app
      template:
        src: flask_nginx.conf.j2
        dest: /etc/nginx/sites-available/flask_app
      notify: restart nginx

    - name: Enable Nginx configuration
      file:
        src: /etc/nginx/sites-available/flask_app
        dest: /etc/nginx/sites-enabled/flask_app
        state: link

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

  handlers:
    - name: restart gunicorn
      systemd:
        name: gunicorn
        state: restarted

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
